### PR TITLE
feat: v0.2.0

### LINKED ISSUE #1: Document types
This library looks amazing! Thank you! 🙏 

I'm not sure if I'm doing something wrong but it seems the types aren't working as expected:

```ts
interface CustomerDocument {
  _id: string
  name: string
  email: string
  phone: string
}

const customers = new MongoDBDataAPI<CustomerDocument>(
  {
    apiKey: process.env.MONGODB_DATA_API_KEY!,
    appId: process.env.MONGODB_DATA_API_APP_ID!,
  },
  {
    dataSource: process.env.MONGODB_DATA_API_DATASOURCE,
    database: process.env.MONGODB_DATA_API_DATABASE,
    collection: "customers",
  }
);

customers.findOne({filter: {_id: "5e9f9b8f9b8f9b8f9b8f9b8f"}}).then(({document}) => {
  if (!document) throw new Error("Customer not found")
  // `document` now has a type of `{ _id: string }`
  // I would expect that `document` would be of type `CustomerDocument`
})
```

It appears that the `document` variable is getting the type of the `filter`.

### PR DESCRIPTION
**Pull request by surmon-china**
**Feature**

- New creator function `createMongoDBDataAPI`

**Fix**

- fix #1 
- [#3 Adjust typescript generics](https://github.com/surmon-china/mongodb-data-api/pull/3)
- [#4 Disable parameter inference](https://github.com/surmon-china/mongodb-data-api/pull/4)

### CODE REVIEW

**Comment by surmon-china** [comment]
@maxfi Hi! there

**Review by lzfee0227 — COMMENTED** [review]
👀

**Review by lzfee0227 — APPROVED** [review]
lgtm

**Comment by maxfi** [comment]
Hi @surmon-china and @lzfee0227. In this release, shall we also include:

- https://github.com/surmon-china/mongodb-data-api/issues/2
- A BSON parser?

If so I'll create PRs for both tomorrow. Thanks.

**Comment by surmon-china** [comment]
@maxfi 

- About #2 is of course PR welcome when we make sure there is no problem with `fetch` compatibility
- Regarding A BSON parser, you need to describe in detail its purpose and design

We can release these features in the next major version. ❤

**Pull request merged**
